apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: {{ .Values.app.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.version }}"
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          env:
          {{- range .Values.app.envVars }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}