app:
  name: emailservice
  namespace: app
  image: gcr.io/google-samples/microservices-demo/emailservice
  version: v0.8.0
  replicaCount: 1
  containerPort: 8080
  envVars:
  - name: PORT
    value: "8080"

servicePort: 5004