app:
  name: paymentservice
  namespace: app
  image: gcr.io/google-samples/microservices-demo/paymentservice
  version: v0.8.0
  replicaCount: 1
  containerPort: 50051
  envVars:
  - name: PORT
    value: "50051"
  - name: DISABLE_PROFILER
    value: "1"

servicePort: 5006